[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/7i.json"

[programs.mainnet]
jare_hydra="ANSsi8dnmwyjQaGNC4PhRMU8WfBgKcvKzC9bPMBiJAPf"

[workspace]
members = [
  "program",
]