[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/7i.json"

[programs.mainnet]
jare_hydra="FXZzBYS58sVq9KBnVWjduZVpYtwpRAViMdtE8HvwBqR1"

[workspace]
members = [
  "program",
]